version: "3"
services:
  app:
    build: .
    command: node build/main.js
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_LOG_WEBHOOK=${DISCORD_LOG_WEBHOOK}
      - LINKETRACK_USER=${LINKETRACK_USER}
      - LINKETRACK_API_KEY=${LINKETRACK_API_KEY}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - UPDATES_CHANNEL=${UPDATES_CHANNEL}
